/* IN HERE GO SELECTOR FUNCTIONS TO CONVERT DATA FROM THE FORMAT THEY ARE IN
 * IN THE REDUX STORE TO FORMAT THE DATA WILL TAKE FOR THE VIEWS.
 * ALLOWING DECOUPLING OF THE FORMAT THE DATA TAKES IN THE APPLICATION STATE
 * WITH THE VIEWS SO THAT IF DATA FORMAT CHANGES IT WON'T AFFECT THE VIEWS
 * AND JUST THESE SELECTOR FUNCTIONS WILL NEED TO CHANGE.
 */
